# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ehr_service_pb2 as ehr__service__pb2


class EhrServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePatient = channel.unary_unary(
                '/ehr.EhrService/CreatePatient',
                request_serializer=ehr__service__pb2.CreatePatientRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.PatientResponse.FromString,
                )
        self.GetPatient = channel.unary_unary(
                '/ehr.EhrService/GetPatient',
                request_serializer=ehr__service__pb2.GetPatientRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.PatientResponse.FromString,
                )
        self.GetAllPatients = channel.unary_unary(
                '/ehr.EhrService/GetAllPatients',
                request_serializer=ehr__service__pb2.GetAllPatientsRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.GetAllPatientsResponse.FromString,
                )
        self.SearchPatientById = channel.unary_unary(
                '/ehr.EhrService/SearchPatientById',
                request_serializer=ehr__service__pb2.SearchPatientByIdRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.PatientResponse.FromString,
                )
        self.UpdatePatient = channel.unary_unary(
                '/ehr.EhrService/UpdatePatient',
                request_serializer=ehr__service__pb2.UpdatePatientRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.PatientResponse.FromString,
                )
        self.DeletePatient = channel.unary_unary(
                '/ehr.EhrService/DeletePatient',
                request_serializer=ehr__service__pb2.DeletePatientRequest.SerializeToString,
                response_deserializer=ehr__service__pb2.DeletePatientResponse.FromString,
                )


class EhrServiceServicer(object):
    """Service definition
    """

    def CreatePatient(self, request, context):
        """Create a new patient record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatient(self, request, context):
        """Get a patient by UUID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPatients(self, request, context):
        """Get all patients with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPatientById(self, request, context):
        """Search patient by patient_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePatient(self, request, context):
        """Update a patient record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePatient(self, request, context):
        """Delete a patient record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EhrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=ehr__service__pb2.CreatePatientRequest.FromString,
                    response_serializer=ehr__service__pb2.PatientResponse.SerializeToString,
            ),
            'GetPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatient,
                    request_deserializer=ehr__service__pb2.GetPatientRequest.FromString,
                    response_serializer=ehr__service__pb2.PatientResponse.SerializeToString,
            ),
            'GetAllPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPatients,
                    request_deserializer=ehr__service__pb2.GetAllPatientsRequest.FromString,
                    response_serializer=ehr__service__pb2.GetAllPatientsResponse.SerializeToString,
            ),
            'SearchPatientById': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPatientById,
                    request_deserializer=ehr__service__pb2.SearchPatientByIdRequest.FromString,
                    response_serializer=ehr__service__pb2.PatientResponse.SerializeToString,
            ),
            'UpdatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePatient,
                    request_deserializer=ehr__service__pb2.UpdatePatientRequest.FromString,
                    response_serializer=ehr__service__pb2.PatientResponse.SerializeToString,
            ),
            'DeletePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePatient,
                    request_deserializer=ehr__service__pb2.DeletePatientRequest.FromString,
                    response_serializer=ehr__service__pb2.DeletePatientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ehr.EhrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EhrService(object):
    """Service definition
    """

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/CreatePatient',
            ehr__service__pb2.CreatePatientRequest.SerializeToString,
            ehr__service__pb2.PatientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/GetPatient',
            ehr__service__pb2.GetPatientRequest.SerializeToString,
            ehr__service__pb2.PatientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/GetAllPatients',
            ehr__service__pb2.GetAllPatientsRequest.SerializeToString,
            ehr__service__pb2.GetAllPatientsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchPatientById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/SearchPatientById',
            ehr__service__pb2.SearchPatientByIdRequest.SerializeToString,
            ehr__service__pb2.PatientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/UpdatePatient',
            ehr__service__pb2.UpdatePatientRequest.SerializeToString,
            ehr__service__pb2.PatientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ehr.EhrService/DeletePatient',
            ehr__service__pb2.DeletePatientRequest.SerializeToString,
            ehr__service__pb2.DeletePatientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
